import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import ReactECharts from 'echarts-for-react';
import './style.css';
const API=import.meta.env.VITE_API_URL||(window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1'?'http://localhost:8000':'');
async function api(path,opt={}){const cfg={...opt,headers:{...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opt.headers||{})}};const r=await fetch(API+path,cfg);if(!r.ok)throw new Error((await r.text())||`HTTP ${r.status}`);if(r.status===204)return null;return r.json()}
const money=n=>`NT$ ${Number(n||0).toLocaleString()}`;
const taiwanTime=value=>{
  if(!value)return '';
  // Backend 若回傳不含時區的時間，視為 UTC，避免 Render(UTC) 與台灣時間相差 8 小時。
  const raw=String(value);
  const d=new Date(/[zZ]|[+-]\d\d:\d\d$/.test(raw)?raw:raw+'Z');
  if(Number.isNaN(d.getTime()))return raw;
  return new Intl.DateTimeFormat('zh-TW',{
    timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',
    hour:'2-digit',minute:'2-digit',hour12:false
  }).format(d);
};
const cats={fern:'蕨類',herb:'香草',vegetable:'蔬菜',flower:'花卉',other:'其他'};
function App(){
 const [tab,setTab]=useState('dashboard'),[plants,setPlants]=useState([]),[zones,setZones]=useState([]),[inv,setInv]=useState([]),[dash,setDash]=useState(null),[analytics,setAnalytics]=useState({death_causes:[],finance_monthly:[]}),[native,setNative]=useState({items:[],count:0,total:18,percent:0}),[sellers,setSellers]=useState([]),[emergency,setEmergency]=useState([]),[composts,setComposts]=useState([]),[zoneFilter,setZoneFilter]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(null);
 const toast=t=>{setNotice(t);setTimeout(()=>setNotice(''),2600)};
 const load=async()=>{try{const [z,p,i,d,a,n,s,e,c]=await Promise.all([api('/zones'),api('/plants'+(zoneFilter?`?zone_id=${zoneFilter}`:'')),api('/inventory'),api('/dashboard'),api('/analytics'),api('/native-species'),api('/sellers'),api('/emergency-care'),api('/compost')]);setZones(z);setPlants(p);setInv(i);setDash(d);setAnalytics(a);setNative(n);setSellers(s);setEmergency(e);setComposts(c)}catch(e){toast('載入失敗：'+e.message)}};
 useEffect(()=>{load()},[zoneFilter]);
 const seed=async()=>{await api('/seed',{method:'POST'});toast('已建立示範場域與庫存');load()};
 return <div className="app">
  <aside><div className="brand"><span className="logo">🌿</span><div><h1>Plantopia</h1><p>Cyber-Botanist Console</p></div></div>
   <Nav tab={tab} setTab={setTab}/><div className="zonebox"><b>場域篩選</b><button className={!zoneFilter?'active':''} onClick={()=>setZoneFilter('')}>🌎 全部場域</button>{zones.map(z=><button className={String(zoneFilter)===String(z.id)?'active':''} key={z.id} onClick={()=>setZoneFilter(z.id)}>🪴 {z.name}</button>)}</div>
   <button className="seed" onClick={seed}>✨ 初始化示範資料</button>
  </aside>
  <main><header><div><h2>{titles[tab]}</h2><span>Final Edition · VS Code / Render Ready</span></div><div className="coin">🪙 {money(dash?.total_net_worth)}</div></header>
   {notice&&<div className="toast">{notice}</div>}
   {tab==='dashboard'&&<Dashboard dash={dash} analytics={analytics} native={native} emergency={emergency} setTab={setTab}/>} 
   {tab==='plants'&&<Plants plants={plants} zones={zones} inv={inv} load={load} toast={toast} setSelected={setSelected}/>} 
   {tab==='gene'&&<Gene plants={plants} native={native} toast={toast}/>} 
   {tab==='inventory'&&<Inventory inv={inv} load={load} toast={toast}/>} 
   {tab==='photos'&&<Photos plants={plants} toast={toast}/>} 
   {tab==='care'&&<Care emergency={emergency} plants={plants} zones={zones} load={load} toast={toast}/>} 
   {tab==='finance'&&<Finance dash={dash} analytics={analytics} sellers={sellers}/>} 
   {tab==='compost'&&<Compost composts={composts} load={load} toast={toast}/>} 
   {selected&&<PlantDetail p={selected} plants={plants} inv={inv} close={()=>setSelected(null)} load={load} toast={toast}/>} 
  </main>
 </div>
}
const titles={dashboard:'溫室控制台',plants:'植栽資產與快捷操作',gene:'基因鏈與 18 種圖鑑',inventory:'RPG 裝備與耗材背包',photos:'Bio-Scan 相片履歷',care:'智慧照顧與出差排程',finance:'財務與賣家分析',compost:'Compost Reactor'};
function Nav({tab,setTab}){return <nav>{[['dashboard','⌂','Dashboard'],['plants','🌱','植栽管理'],['gene','🧬','Gene Tree'],['inventory','🎒','資產背包'],['photos','📷','Photo Log'],['care','💧','智慧照顧'],['finance','📊','財務分析'],['compost','♻️','堆肥反應爐']].map(([k,i,t])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><span>{i}</span>{t}</button>)}</nav>}
function Dashboard({dash,analytics,native,emergency,setTab}){const death=analytics.death_causes||[],fin=analytics.finance_monthly||[];return <>
 <section className="stats"><Stat t="存活植栽" v={dash?.living_plants||0} sub="Active Plants"/><Stat t="植物估值" v={money(dash?.plant_market_value)} sub="Live Value"/><Stat t="已實現淨利" v={money(dash?.realized_profit)} sub="Realized Profit"/><Stat t="累計損耗" v={money(dash?.total_losses)} sub="Plant Loss"/><Stat t="採收量" v={`${dash?.total_harvest_g||0} g`} sub="Harvest"/></section>
 <section className="grid2"><Panel title="🧬 原生種收集進度"><div className="collection"><strong>{native.count}/{native.total}</strong><span>{native.percent}%</span></div><div className="progress"><i style={{width:`${native.percent}%`}}/></div><button onClick={()=>setTab('gene')}>查看圖鑑</button></Panel>
 <Panel title="🚨 緊急照顧 Top 5">{emergency.slice(0,5).map(x=><div className="listrow" key={x.id}><span>#{x.id} {x.name}</span><b>{x.urgency.toFixed(2)}</b></div>)}{!emergency.length&&<Empty/>}</Panel></section>
 <section className="grid2"><Panel title="☠️ 死因分析"><Chart option={{tooltip:{trigger:'item'},series:[{type:'pie',radius:['45%','72%'],data:death}]}} empty={!death.length}/></Panel><Panel title="💰 月度現金流"><Chart option={{xAxis:{type:'category',data:fin.map(x=>x.month)},yAxis:{type:'value'},series:[{type:'bar',data:fin.map(x=>x.net_cashflow)}],tooltip:{trigger:'axis'}}} empty={!fin.length}/></Panel></section>
 {dash?.low_stock?.length>0&&<Panel title="⚠️ 低庫存警報"><div className="alerts">{dash.low_stock.map(x=><span key={x.id}>{x.name} 剩餘 {x.remaining_pct}%</span>)}</div></Panel>}</>}
function Stat({t,v,sub}){return <div className="stat"><span>{t}</span><strong>{v}</strong><small>{sub}</small></div>}
function Panel({title,children}){return <section className="panel"><h3>{title}</h3>{children}</section>}
function Chart({option,empty}){return empty?<Empty/>:<ReactECharts style={{height:280}} option={{backgroundColor:'transparent',textStyle:{color:'#dff7e8'},...option}}/>}
function Empty(){return <p className="muted">目前尚無資料</p>}

function Plants({plants,zones,inv,load,toast,setSelected}){const [f,setF]=useState({name:'',category:'fern',species_code:'',rarity:'common',propagation_method:'',purchase_cost:'',market_value:'',watering_interval_days:3,drought_tolerance_days:5,zone_id:'',seller_name:'',parent_id:'',father_id:''});
 const submit=async e=>{e.preventDefault();try{const b={...f,purchase_cost:+f.purchase_cost,market_value:+f.market_value,watering_interval_days:+f.watering_interval_days,drought_tolerance_days:+f.drought_tolerance_days,zone_id:f.zone_id?+f.zone_id:null,parent_id:f.parent_id?+f.parent_id:null,father_id:f.father_id?+f.father_id:null};await api('/plants',{method:'POST',body:JSON.stringify(b)});toast('✨ Task Complete：植栽已建立');setF({...f,name:'',species_code:'',propagation_method:'',purchase_cost:'',market_value:'',zone_id:'',seller_name:'',parent_id:'',father_id:''});load()}catch(e){toast(e.message)}};
 const act=async(type,p)=>{try{if(type==='water')await api(`/plants/${p.id}/water`,{method:'POST'});if(type==='sell'){const v=Number(prompt('請輸入售價'));if(!v)return;const r=await api(`/plants/${p.id}/sell`,{method:'POST',body:JSON.stringify({sale_price:v})});alert(`售出完成\n淨利：${money(r.net_profit)}`)}if(type==='death'){const cause=prompt('死因：生理枯死 / 過濕爛根 / 真菌細菌病害 / 蟲害 / 蛀心蟲 / 曬傷');if(!cause)return;await api(`/plants/${p.id}/death`,{method:'POST',body:JSON.stringify({cause})})}if(type==='harvest'){const v=Number(prompt('採收重量（g）'));if(!v)return;await api(`/plants/${p.id}/harvest`,{method:'POST',body:JSON.stringify({amount:v,unit:'g'})})}toast('操作完成');load()}catch(e){toast(e.message)}};
  return <><Panel title="⚡ 新增植栽 / Buy-in Form"><form className="formgrid" onSubmit={submit}>
   <input required placeholder="植物名稱（例：龜背芋）" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/>
   <select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option disabled value="">植物類別</option>{Object.entries(cats).map(([v,t])=><option value={v} key={v}>類別：{t}</option>)}</select>
   <input placeholder="原生種代碼（選填，P01～P18）" value={f.species_code} onChange={e=>setF({...f,species_code:e.target.value.toUpperCase()})}/>
   <select value={f.rarity} onChange={e=>setF({...f,rarity:e.target.value})}><option value="common">稀有度：普通</option><option value="rare">稀有度：稀有</option><option value="hybrid">稀有度：雜交 ⭐</option></select>
   <input placeholder="繁殖方式（例：扦插、分株、播種）" value={f.propagation_method} onChange={e=>setF({...f,propagation_method:e.target.value})}/>
   <input placeholder="賣家名稱（選填）" value={f.seller_name} onChange={e=>setF({...f,seller_name:e.target.value})}/>
   <input type="number" min="0" placeholder="購入價格 NT$（例：1500）" value={f.purchase_cost} onChange={e=>setF({...f,purchase_cost:e.target.value})}/>
   <input type="number" min="0" placeholder="目前估值 NT$（例：2200）" value={f.market_value} onChange={e=>setF({...f,market_value:e.target.value})}/>
   <select value={f.zone_id} onChange={e=>setF({...f,zone_id:e.target.value})}><option value="">種植場域：未指定</option>{zones.map(z=><option key={z.id} value={z.id}>種植場域：{z.name}</option>)}</select>
   <select value={f.parent_id} onChange={e=>setF({...f,parent_id:e.target.value})}><option value="">母株：無／不指定</option>{plants.map(p=><option key={p.id} value={p.id}>母株：#{p.id} {p.name}</option>)}</select>
   <select value={f.father_id} onChange={e=>setF({...f,father_id:e.target.value})}><option value="">父本：無／不指定</option>{plants.map(p=><option key={p.id} value={p.id}>父本：#{p.id} {p.name}</option>)}</select>
   <button className="primary">建立植栽</button>
  </form><p className="muted">提示：原生種代碼、賣家、場域與親本資料可依實際情況留空；購入價格是實際花費，目前估值是你認為植物現在的市場價值。</p></Panel>
 <Panel title="🗺️ 植栽資產卡"><div className="cards">{plants.map(p=><PlantCard key={p.id} p={p} act={act} details={()=>setSelected(p)}/>)}</div>{!plants.length&&<Empty/>}</Panel></>}
function PlantCard({p,act,details}){const dead=p.status==='dead';return <div className={`plant ${p.status}`}><div className="planttop"><b>{dead?'🪦':'🌱'} #{p.id} {p.name}</b><span className="rarity">{p.rarity==='hybrid'?'⭐ HYBRID':p.rarity}</span></div><small>{cats[p.category]||p.category} · Zone {p.zone_id||'—'} · {p.species_code||'未編圖鑑'}</small><label>HP</label><div className="bar hp"><i style={{width:`${p.hp}%`}}/></div><div className="plantmoney">估值 {money(p.market_value)}</div>{p.status==='alive'?<div className="actions"><button title="記錄澆水" aria-label="記錄澆水" onClick={()=>act('water',p)}>💧 澆水</button><button title="記錄採收" aria-label="記錄採收" onClick={()=>act('harvest',p)}>🌾 採收</button><button title="售出植物" aria-label="售出植物" onClick={()=>act('sell',p)}>💰 售出</button><button title="記錄死亡" aria-label="記錄死亡" onClick={()=>act('death',p)}>☠ 死亡</button><button title="更多資料與操作" aria-label="更多資料與操作" onClick={details}>⋯ 更多</button></div>:<div className="tomb">{p.status==='dead'?`死因：${p.death_cause}`:p.status==='sold'?`已售出 ${money(p.sale_price)}`:`已贈與 ${p.transfer_to||''}`}</div>}</div>}

function PlantDetail({p,plants,inv,close,load,toast}){const pots=inv.filter(x=>x.kind==='equipment'),meds=inv.filter(x=>x.kind==='consumable');const prop=async()=>{const count=Number(prompt('分株數量'));if(!count)return;const pot=Number(prompt('盆器庫存 ID（可留空取消盆器扣除）'))||null;try{await api(`/plants/${p.id}/propagate`,{method:'POST',body:JSON.stringify({count,pot_item_id:pot,propagation_cost_each:0})});toast('🌱 EXP +100：分株完成');close();load()}catch(e){toast(e.message)}};const transfer=async()=>{const recipient=prompt('贈與對象');if(!recipient)return;await api(`/plants/${p.id}/transfer`,{method:'POST',body:JSON.stringify({recipient})});toast('已記錄贈與');close();load()};const repot=async()=>{const newId=Number(prompt('新盆器 ID：\n'+pots.map(x=>`${x.id}: ${x.name}(${x.quantity})`).join('\n')));if(!newId)return;const mid=Number(prompt('介質 ID（可取消）：\n'+meds.map(x=>`${x.id}: ${x.name}`).join('\n')))||null;const amt=mid?Number(prompt('使用介質量'))||0:0;try{await api(`/plants/${p.id}/repot`,{method:'POST',body:JSON.stringify({new_pot_item_id:newId,medium_item_id:mid,medium_amount:amt})});toast('換盆與庫存連動完成');load()}catch(e){toast(e.message)}};return <div className="modalbg" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button><h3>🌿 #{p.id} {p.name}</h3><div className="detailgrid"><span>母株</span><b>{p.parent_id?`#${p.parent_id}`:'—'}</b><span>父本</span><b>{p.father_id?`#${p.father_id}`:'—'}</b><span>繁殖</span><b>{p.propagation_method||'—'}</b><span>成本</span><b>{money(p.purchase_cost)}</b></div><div className="modalactions"><button onClick={prop}>🌱 分株</button><button onClick={repot}>🪴 換盆</button><button onClick={transfer}>🎁 贈與</button></div></div></div>}

function Gene({plants,native,toast}){const [root,setRoot]=useState(''),[tree,setTree]=useState(null);const loadTree=async()=>{if(!root)return;try{setTree(await api(`/gene-tree/${root}`))}catch(e){toast(e.message)}};return <><section className="grid2"><Panel title="🏆 18 種原生種成就圖鑑"><div className="collection"><strong>{native.count}/{native.total}</strong><span>{native.percent}%</span></div><div className="dex">{native.items.map(x=><div className={x.collected?'got':''} key={x.code}><b>{x.collected?'✅':'◻️'} {x.code}</b><span>{x.name}</span></div>)}</div></Panel><Panel title="🧬 Gene Tree"><div className="inline"><select value={root} onChange={e=>setRoot(e.target.value)}><option value="">選擇母株</option>{plants.map(p=><option key={p.id} value={p.id}>#{p.id} {p.name}</option>)}</select><button className="primary" onClick={loadTree}>生成基因鏈</button></div>{tree?<Tree n={tree}/>:<Empty/>}</Panel></section></>}
function Tree({n}){return <ul className="tree"><li><div><b>#{n.id} {n.name}</b>{n.father_id&&<small> × 父本 #{n.father_id}</small>}</div>{n.children?.length>0&&<div>{n.children.map(c=><Tree n={c} key={c.id}/>)}</div>}</li></ul>}

function Inventory({inv,load,toast}){const [f,setF]=useState({kind:'equipment',name:'',quantity:1,unit:'pcs',unit_cost:0,capacity:'',remaining:'',reusable:true,quality_level:1});const submit=async e=>{e.preventDefault();const b={...f,quantity:+f.quantity,unit_cost:+f.unit_cost,capacity:f.capacity?+f.capacity:null,remaining:f.remaining?+f.remaining:null,quality_level:+f.quality_level};try{await api('/inventory',{method:'POST',body:JSON.stringify(b)});toast('🎒 補貨完成');setF({...f,name:'',quantity:1,unit_cost:0});load()}catch(e){toast(e.message)}};return <><Panel title="📦 資產補貨"><form className="formgrid" onSubmit={submit}><select value={f.kind} onChange={e=>setF({...f,kind:e.target.value})}><option value="equipment">固定資產 / 盆器</option><option value="consumable">消耗品</option></select><input required placeholder="名稱" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input type="number" min="0.01" step="0.01" value={f.quantity} onChange={e=>setF({...f,quantity:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="單價" value={f.unit_cost} onChange={e=>setF({...f,unit_cost:e.target.value})}/><input placeholder="容量（消耗品）" value={f.capacity} onChange={e=>setF({...f,capacity:e.target.value})}/><input placeholder="剩餘量" value={f.remaining} onChange={e=>setF({...f,remaining:e.target.value})}/><button className="primary">補貨</button></form></Panel><Panel title="🎒 RPG Inventory"><div className="inventory">{inv.map(x=>{const pct=x.capacity&&x.remaining!=null?Math.max(0,Math.min(100,x.remaining/x.capacity*100)):null;return <div className="slot" key={x.id}><div><b>#{x.id} {x.name}</b><span>{'⭐'.repeat(x.quality_level||1)}</span></div><small>{x.kind==='equipment'?'固定資產':'消耗品'} · {x.quantity} {x.unit}</small>{pct!=null&&<><div className="bar"><i style={{width:`${pct}%`}}/></div><em className={pct<20?'low':''}>{pct.toFixed(1)}%</em></>}</div>})}</div></Panel></>}

function Photos({plants,toast}){const [pid,setPid]=useState(''),[photos,setPhotos]=useState([]),[angle,setAngle]=useState('全景'),[file,setFile]=useState(null),[note,setNote]=useState('');const loadPhotos=async id=>{setPid(id);setPhotos(id?await api(`/plants/${id}/photos`):[])};const upload=async e=>{e.preventDefault();if(!pid||!file)return toast('請選植物與照片');const fd=new FormData();fd.append('angle',angle);fd.append('note',note);fd.append('file',file);try{await api(`/plants/${pid}/photos`,{method:'POST',body:fd});toast('📷 Bio-Scan 完成');setFile(null);setNote('');loadPhotos(pid)}catch(e){toast(e.message)}};return <><Panel title="📷 四角度 Bio-Scan"><form className="formgrid" onSubmit={upload}><select value={pid} onChange={e=>loadPhotos(e.target.value)}><option value="">選擇要記錄的植栽</option>{plants.map(p=><option value={p.id} key={p.id}>植栽：#{p.id} {p.name}</option>)}</select><select value={angle} onChange={e=>setAngle(e.target.value)}>{['全景','葉正反面','莖基部','介質'].map(x=><option key={x} value={x}>拍攝角度：{x}</option>)}</select><input type="file" accept="image/*" title="選擇植物照片" onChange={e=>setFile(e.target.files?.[0])}/><input placeholder="照片備註（選填，例如：新葉展開、葉片黃斑）" value={note} onChange={e=>setNote(e.target.value)}/><button className="primary">上傳照片</button></form><p className="muted">建議同一株植物依序記錄：全景、葉正反面、莖基部、介質，方便之後比較生長變化。</p></Panel><Panel title="🕘 生長時間軸（台灣時間）"><div className="gallery">{photos.map(x=><figure key={x.id}><img src={API+x.url}/><figcaption><b>{x.angle}</b><small>{taiwanTime(x.created_at)}</small><span>{x.note}</span></figcaption></figure>)}</div>{!photos.length&&<Empty/>}</Panel></>}

function Care({emergency,plants,zones,load,toast}){const [loc,setLoc]=useState('臺中市'),[wx,setWx]=useState(null);const weather=async()=>setWx(await api('/weather?location='+encodeURIComponent(loc)));return <section className="grid2"><Panel title="🚨 出差緊急照顧排程"><div className="schedule">{emergency.map((x,i)=><div key={x.id}><strong>#{i+1}</strong><span>#{x.id} {x.name}</span><small>{x.days_since_water} 天未澆 · 耐旱 {x.drought_tolerance_days} 天</small><b>Urgency {x.urgency}</b></div>)}</div>{!emergency.length&&<Empty/>}</Panel><Panel title="🌧️ 中央氣象署連動"><div className="inline"><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="臺中市"/><button className="primary" onClick={weather}>讀取預報</button></div>{wx&&<div className={`weather ${wx.rain_expected?'rain':''}`}><strong>{wx.rain_expected?'🌧️ 預期降雨：露天澆水延後 1 天':'☀️ 無自動延後'}</strong><p>{wx.message}</p>{!wx.enabled&&<small>在 backend/.env 或 PowerShell 設定 CWA_API_KEY 後即可啟用正式資料。</small>}</div>}<p className="muted">露天且無雨遮的場域才套用降雨延後。</p></Panel></section>}

function Finance({dash,analytics,sellers}){const fin=analytics.finance_monthly||[];return <><section className="stats"><Stat t="總資產" v={money(dash?.total_net_worth)}/><Stat t="累計投入" v={money(dash?.total_purchases)}/><Stat t="累計售出" v={money(dash?.total_sales)}/><Stat t="已實現淨利" v={money(dash?.realized_profit)}/></section><section className="grid2"><Panel title="📈 財務趨勢"><Chart empty={!fin.length} option={{xAxis:{type:'category',data:fin.map(x=>x.month)},yAxis:{type:'value'},tooltip:{trigger:'axis'},series:[{type:'line',smooth:true,data:fin.map(x=>x.net_cashflow)}]}}/></Panel><Panel title="🏪 賣家 CP 值排行"><div className="ranking">{sellers.map((s,i)=><div key={s.id}><strong>#{i+1}</strong><span>{s.name}</span><small>存活率 {s.survival_rate}% · 平均成本 {money(s.avg_cost)}</small><b>{s.cp_score}</b></div>)}</div>{!sellers.length&&<Empty/>}</Panel></section></>}

function Compost({composts,load,toast}){const [f,setF]=useState({name:'',compost_type:'hot',carbon_weight:30,nitrogen_weight:1,moisture_pct:50});const submit=async e=>{e.preventDefault();try{const r=await api('/compost',{method:'POST',body:JSON.stringify({...f,carbon_weight:+f.carbon_weight,nitrogen_weight:+f.nitrogen_weight,moisture_pct:+f.moisture_pct})});alert(`C/N = ${r.cn_ratio}\n${r.suggestion}`);toast('♻️ 反應爐紀錄完成');load()}catch(e){toast(e.message)}};return <><Panel title="♻️ C/N Ratio Calculator"><form className="formgrid" onSubmit={submit}><input required placeholder="批次名稱" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select value={f.compost_type} onChange={e=>setF({...f,compost_type:e.target.value})}><option value="hot">高溫堆肥</option><option value="cold">低溫堆肥</option></select><input type="number" step="0.1" min="0" value={f.carbon_weight} onChange={e=>setF({...f,carbon_weight:e.target.value})} title="高碳材料重量"/><input type="number" step="0.1" min="0.1" value={f.nitrogen_weight} onChange={e=>setF({...f,nitrogen_weight:e.target.value})} title="高氮材料重量"/><input type="number" min="0" max="100" value={f.moisture_pct} onChange={e=>setF({...f,moisture_pct:e.target.value})} title="濕度%"/><button className="primary">開始試算</button></form><p className="muted">輸入高碳材料重量 ÷ 高氮材料重量作為教學型 C/N 配比指標，系統以 25–35 作為目標提醒區間。</p></Panel><Panel title="🧪 發酵批次"><div className="inventory">{composts.map(x=><div className="slot" key={x.id}><div><b>{x.name}</b><span>{x.stage}</span></div><strong>C/N {x.cn_ratio}</strong><small>濕度 {x.moisture_pct}% · {x.compost_type==='hot'?'高溫':'低溫'}</small><p>{x.suggestion}</p></div>)}</div>{!composts.length&&<Empty/>}</Panel></>}
createRoot(document.getElementById('root')).render(<App/>);
